### ISSUE TITLE
ImportError: cannot import name 'SketchData' from 'dataset'

### ISSUE THREAD

**Issue by Kane-LAU** [samxuxiang/SkexGen#4]
First of all, thank you very much for your contribution to intelligent CAD generation. It's great work. However, I encountered some issues while attempting to run the repository. 

```
python train_sketch.py --train_data data/cad_data/train_deduplicate_s.pkl --output proj_log/exp_sketch --invalid data/cad_data/train_invalid.pkl  --val_data data/cad_data/val.pkl --bit 6 --maxlen 200 --batchsize 128 --device 0
```

bug:
```
SkexGen\train_sketch.py", line 4, in <module>
    from dataset import SketchData
ImportError: cannot import name 'SketchData' from 'dat
```

Can you provide me with some advice? I greatly appreciate it.

**Comment by samxuxiang** [comment]
I tested the code again and did not encounter this error. Can you try running with the provided docker image and also download the [processed data](https://drive.google.com/file/d/1so_CCGLIhqGEDQxMoiR--A4CQk4MjuOp/view?usp=sharing). Let me know if you run into the same problem again. I tried it on a clean env and things should work fine. 
![image](https://github.com/samxuxiang/SkexGen/assets/22716231/792287d6-7d0a-4d98-b98d-96c0e9fbe2a8)

**Comment by Kane-LAU** [comment]
Thanks for your reply. 
but i cannot find "SktechData" function  at /utils/dataset.py,
```
ImportError: cannot import name 'SketchData' from 'dataset' (D:\xin_code\SkexGen\utils\dataset.py)
```
https://github.com/samxuxiang/SkexGen/blob/main/utils/dataset.py

![image](https://github.com/samxuxiang/SkexGen/assets/42459125/ae632b1c-8987-4712-8e94-0eb9be586659)

maybe you can check the code again 😊

**Comment by samxuxiang** [comment]
Hi, you can find SketchData class in the parent folder under dataset.py 
![image](https://github.com/samxuxiang/SkexGen/assets/22716231/12a85b9b-6825-4b30-a970-3be45855d166)
