### ISSUE TITLE
TESTING too many times

### ISSUE THREAD

**Issue by Kane-LAU** [samxuxiang/SkexGen#5]
I succeded to run the code
```
python train_sketch.py --train_data data/cad_data/train_deduplicate_s.pkl --output proj_log/exp_sketch --invalid data/cad_data/train_invalid.pkl  --val_data data/cad_data/val.pkl --bit 6 --maxlen 200 --batchsize 128 --device 0

```
![image](https://github.com/samxuxiang/SkexGen/assets/42459125/b4ee961a-900c-496c-8aa7-f0094d5000ba)

but testing too many times and never stop😂~ how can i fix it ?  Thank you in advance ~

**Comment by Kane-LAU** [comment]
@samxuxiang 😀

**Comment by samxuxiang** [comment]
You can simply comment out this line, this is a small bug that prints every time. https://github.com/samxuxiang/SkexGen/blob/c38f30e8ac40aabfa2a71d6842cc585faa9b9862/train_sketch.py#L147

Actual testing happen every 30 epoch, and you can adjust the frequency accordingly. https://github.com/samxuxiang/SkexGen/blob/c38f30e8ac40aabfa2a71d6842cc585faa9b9862/train_sketch.py#L148
