### ISSUE TITLE
Where is the code for caculating "Novel" score?

### ISSUE THREAD

**Issue by SpartanH7** [samxuxiang/SkexGen#6]
I didn't find the code for caculating "Unique" score and "Novel" score in **eval_cad.py**, I guess I can use **deduplicate.py** to get the "Unique" score, but for the "Novel" score?
Thanks for answering!

**Comment by samxuxiang** [comment]
Hi, the code used for computing novel and unique can be find here https://github.com/samxuxiang/hnc-cad/blob/6b490123ad5757313c446ccd1a4fce1db8d2869d/gen/rand_gen.py#L127

**Comment by SpartanH7** [comment]
ok, thanks!
