### ISSUE TITLE
Where is the code for evaling sketch generation task?

### ISSUE THREAD

**Issue by kk7122** [samxuxiang/SkexGen#7]

**Comment by kk7122** [comment]
And MMD and JSD are too low when testing, how can I fix it . Thank you in advance.
![image](https://github.com/samxuxiang/SkexGen/assets/55452494/e24662f9-92ee-4a7a-a5c7-2916129914b8)

**Comment by kk7122** [comment]
@samxuxiang

**Comment by samxuxiang** [comment]
@memory-tech Hi, you can find the script for training and evaluating FID score [here](https://drive.google.com/file/d/1zf61Wcr79AcWvUT8hFOVvOHwQShRkJxL/view?usp=sharing). For CAD evaluation, please refer to the updated [script](https://github.com/samxuxiang/hnc-cad/blob/111a86d82b28c7a5fa4b920f96f4df0f23bdb89b/gen/rand_gen.py#L127) for novel and unique scores, and [eval_cad.py](https://github.com/samxuxiang/hnc-cad/blob/main/gen/eval_cad.py) for MMD,COV, and JSD. The post-processed test data is available for download [here](https://drive.google.com/file/d/1FhONYaJTK2vkayfDKH5TaHXDyjl2f4f-/view?usp=sharing). You can find more instructions on our new hnc-cad project [page](https://github.com/samxuxiang/hnc-cad). Let me know if you have more issues.

**Comment by kk7122** [comment]
Thanks for your reply! Is there any code error when testing MMD and JSD, they are too low when testing, shown in the pictuce above.  @samxuxiang

**Comment by samxuxiang** [comment]
The coverage is much lower than expected. I wonder if you have visualize the generated results.This could happen when network is generating a lot of simple cubes and cylinders, which appear very often in deepcad dataset. We use de-duplication on the training set to avoid generating the same cad / code sequence repeatedly. Please refer to the data processing and [code extraction](https://github.com/samxuxiang/hnc-cad/blob/111a86d82b28c7a5fa4b920f96f4df0f23bdb89b/codebook/extract_code.py#L86).

**Comment by kk7122** [comment]
ok, thanks!

**Comment by MHassan1122** [comment]
I am experiencing the same issue: the MMD and JSD values are significantly lower compared to those reported in the paper, and the coverage is also lower than expected, despite using the preprocessed test data.
